package hangman

import (
	"fmt"
	"os"
	"time"
)

func Starting() {
	Clear()
	var choix string
	for choix != "1" && choix != "Q" && choix != "q" {
		StartGame()
		fmt.Scan(&choix)
		Clear()
		if choix == "1" {
			fmt.Println("⠀  ⠀   (\\__/)")
			fmt.Println("       (•ㅅ•)      Let's go Baby !")
			fmt.Println("    ＿ノヽ ノ＼＿      juste avant Kévin le gros bg")
			fmt.Println("`/　`/ ⌒Ｙ⌒ Ｙ  ヽ     va t'expliquer les regles ")
			fmt.Println("( 　(三ヽ人　 /　  |")
			fmt.Println("|　ﾉ⌒＼ ￣￣ヽ   ノ")
			fmt.Println("ヽ＿＿＿＞､＿_／")
			fmt.Println("       ｜( 王 ﾉ〈")
			fmt.Println("       /ﾐ`ー―彡\\ ")
			fmt.Println("      / ╰    ╯ \\ ")
			time.Sleep(2850 * time.Millisecond)
			Clear()
			fmt.Println("       (\\ __ /) ")
			fmt.Println("        (UwU)           |￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
			fmt.Println("    ＿ノ ヽ ノ＼＿             Yo mec moi c'est Kévin, je vais t'expliquer les regles.")
			fmt.Println(" /　`/ ⌒Ｙ⌒ Ｙ　 \\            le but du jeu, c'est easy : tu dois deviner toutes")
			fmt.Println("( 　(三ヽ人　 /　　|           les lettres qui vont composer un mot. Tu as peut-être un ")
			fmt.Println("|　ﾉ⌒＼ ￣￣ヽ　 ノ           nombre limité de shots, et les thèmes sont déjà en place.")
			fmt.Println("ヽ＿＿＿＞､＿＿／               Dès que tu mets la main sur une lettre, je te la balance. ")
			fmt.Println("    ｜( 王 ﾉ〈              Si tu gagnes gg mais si tu te plantes, on va te faire un  ")
			fmt.Println("    /ﾐ`ー―彡\\               sale boulot...")
			fmt.Println("  / ╰       ╯ \\        |                                                                   | ")
			fmt.Println("                        ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
			time.Sleep(18000 * time.Millisecond)
			Clear()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println("                                                                                ∧＿∧")
			fmt.Println("                                                                                 (｡･ω･｡)つ━☆・*。")
			fmt.Println("                                                                                ⊂/　     /　   ・゜")
			fmt.Println("                                                                                しーＪ　　　     °。+ * 。　")
			fmt.Println("　　　　　                                                                                .・゜")
			fmt.Println("　　　　　                                                                                ゜｡ﾟﾟ･｡･ﾟﾟ。")
			fmt.Println("　　　　                                                                                  　ﾟ。　 　｡ﾟ")
			fmt.Println("                                                                                          　ﾟ･｡･ﾟ ")
			time.Sleep(1000 * time.Millisecond)
			Clear()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println()
			fmt.Println("                                                                                 Miaw miaw Bracadabra")
			time.Sleep(800 * time.Millisecond)
			Clear()
		}
		if choix == "q" || choix == "Q" {
			os.Exit(0)
		}
	}
}

func StartGame() {
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println("                                                                                ──────▄▀▄─────▄▀▄")
	fmt.Println("                                                                                ─────▄█░░▀▀▀▀▀░░█▄")
	fmt.Println("                                                                                ─▄▄──█░░░░░░░░░░░█──▄▄")
	fmt.Println("                                                                                █▄▄█─█░░▀░░┬░░▀░░█─█▄▄█")
	fmt.Println("                                                    ╔═══════════════════════════════════════════════════════════════════════════╗")
	fmt.Println("                                                            ██╗░░██╗░█████╗░███╗░░██╗░██████╗░███╗░░░███╗░█████╗░███╗░░██╗")
	fmt.Println("                                                            ██║░░██║██╔══██╗████╗░██║██╔════╝░████╗░████║██╔══██╗████╗░██║")
	fmt.Println("                                                            ███████║███████║██╔██╗██║██║░░██╗░██╔████╔██║███████║██╔██╗██║")
	fmt.Println("                                                            ██╔══██║██╔══██║██║╚████║██║░░╚██╗██║╚██╔╝██║██╔══██║██║╚████║")
	fmt.Println("                                                            ██║░░██║██║░░██║██║░╚███║╚██████╔╝██║░╚═╝░██║██║░░██║██║░╚███║")
	fmt.Println("                                                            ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝░╚═════╝░╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝")
	fmt.Println("                                                                ☆ ° ✧　 　 · Tape [1] pour commencer ☆ ° ✧　 　 ·")
	fmt.Println("                                                                                        ou")
	fmt.Println("                                                                          ✧ Tape [Q] pour qui quitter ✧")
	fmt.Println("                                                    ╚═══════════════════════════════════════════════════════════════════════════╝")
}
